version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"